name: local_notifications
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^12.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  sqflite: ^2.2.4+1
  http: ^0.13.5
  dio: ^4.0.6
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true